"""pi_tui.engine — Textual-free 终端 UI 引擎。

对齐 TS pi-tui 的内置渲染器 / 输入解析 / 组件树：
终端由本包直接控制（raw 模式、alt-screen、光标、OSC），
组件渲染为单元格行后按行差分写入屏幕。
"""

from .app import App, OverlayWidget
from .cells import Cell, Line, blank_line, line_from_text, line_to_ansi
from .editor_component import EditorComponent
from .fuzzy import FuzzyMatch, fuzzy_filter, fuzzy_match
from .kill_ring import KillRing
from .layout import (
    LayoutContext,
    allocate_stack_sizes,
    box_at,
    get_scroll_view_box,
    get_scroll_views_at,
    layout_component,
    render_cached,
    render_layout_frame,
    visible_stack_entries,
)
from .latex import render_latex
from .layout_node import (
    LayoutBox,
    LayoutFrame,
    LayoutRect,
    ScrollLayoutNode,
    StackLayoutEntry,
    StackLayoutNode,
    get_layout_node,
)
from .markdown_render import (
    DefaultTextStyle,
    MarkdownOptions,
    MarkdownTheme,
    ThemeMarkdownTheme,
    render_markdown_lines,
)
from .keys import Key, KeyEvent, KeyParser, MouseEvent, normalize_key_name, parse_input
from .stdin_buffer import StdinBuffer, is_complete_sequence
from .terminal import FakeTerminal, ProcessTerminal, ScreenBuffer, Terminal, TerminalProtocol
from .text import (
    markup_to_text,
    render_group,
    render_markdown,
    render_markup,
    render_renderable,
    strip_ansi,
    visible_width,
)
from .undo_stack import UndoStack
from .word_navigation import find_word_backward, find_word_forward
from .widgets import (
    Box,
    CancellableLoader,
    Container,
    Editor,
    HStack,
    Horizontal,
    Input,
    Label,
    Loader,
    Markdown,
    Message,
    ScrollView,
    SelectItem,
    SelectList,
    SettingItem,
    SettingsList,
    Spacer,
    Static,
    Text,
    TruncatedText,
    VStack,
    Vertical,
    Widget,
)

__all__ = [
    "App",
    "OverlayWidget",
    "Cell",
    "Line",
    "blank_line",
    "line_from_text",
    "line_to_ansi",
    "DefaultTextStyle",
    "LayoutBox",
    "LayoutContext",
    "LayoutFrame",
    "LayoutRect",
    "MarkdownOptions",
    "MarkdownTheme",
    "ThemeMarkdownTheme",
    "render_latex",
    "render_markdown_lines",
    "ScrollLayoutNode",
    "StackLayoutEntry",
    "StackLayoutNode",
    "allocate_stack_sizes",
    "box_at",
    "get_layout_node",
    "get_scroll_view_box",
    "get_scroll_views_at",
    "layout_component",
    "render_cached",
    "render_layout_frame",
    "visible_stack_entries",
    "EditorComponent",
    "FuzzyMatch",
    "fuzzy_filter",
    "fuzzy_match",
    "KillRing",
    "UndoStack",
    "find_word_backward",
    "find_word_forward",
    "StdinBuffer",
    "is_complete_sequence",
    "Key",
    "KeyEvent",
    "KeyParser",
    "MouseEvent",
    "normalize_key_name",
    "parse_input",
    "FakeTerminal",
    "ProcessTerminal",
    "ScreenBuffer",
    "Terminal",
    "TerminalProtocol",
    "markup_to_text",
    "render_group",
    "render_markdown",
    "render_markup",
    "render_renderable",
    "strip_ansi",
    "visible_width",
    "Box",
    "CancellableLoader",
    "Container",
    "Editor",
    "HStack",
    "Horizontal",
    "Input",
    "Label",
    "Loader",
    "Markdown",
    "Message",
    "ScrollView",
    "SelectItem",
    "SelectList",
    "SettingItem",
    "SettingsList",
    "Spacer",
    "Static",
    "Text",
    "TruncatedText",
    "VStack",
    "Vertical",
    "Widget",
]
