"""
pi-ai  统一管理不同模型的 API,返回一个一致的 AI 调用接口。

暂支持 Openai、Deepseek、Ollama 与 Faux(测试用假 Provider)
"""

from .utils._event_stream import AssistantMessageEventStream, EventStream
from .utils.cost import calculate_cost
from .types import (
    AgentMessage,
    AnthropicMessagesCompat,
    AssistantImages,
    AssistantMessage,
    AssistantMessageDiagnostic,
    AssistantMessageEvent,
    BaseContent,
    BaseEvent,
    BaseMessage,
    BedrockCompat,
    CacheRetention,
    ChatTemplateKwargValue,
    ChatTemplateKwargVar,
    CodeContent,
    ConstrainedSamplingConfig,
    ContentBlock,
    Context,
    Cost,
    DoneEvent,
    ErrorEvent,
    GrammarFormat,
    GrammarSampling,
    GrammarVariants,
    AsyncHTTPClient,
    ImageContent,
    ImagesApi,
    ImagesContext,
    ImagesFunction,
    ImagesInputContent,
    ImagesModel,
    ImagesOptions,
    ImagesOutputContent,
    ImagesProviderId,
    ImagesStopReason,
    JsonSchemaSampling,
    KnownImagesApi,
    KnownImagesProvider,
    ApiId,
    MemoryStore,
    Message,
    Model,
    ModelCompat,
    ModelCost,
    ModelCostRates,
    ModelCostTier,
    ModelInput,
    ModelOutput,
    ModelThinkingLevel,
    ProviderId,
    OpenAICompletionsCompat,
    OpenAIResponsesCompat,
    OpenRouterRouting,
    ProviderEnv,
    ProviderHeaders,
    ProviderImages,
    ProviderImagesOptions,
    ProviderResponse,
    ProviderStreamOptions,
    ProviderStreams,
    SessionAffinityFormat,
    SimpleStreamOptions,
    StartEvent,
    StopReason,
    StreamFunction,
    StreamOptions,
    SystemMessage,
    TextContent,
    TextDeltaEvent,
    TextEndEvent,
    TextSignatureV1,
    TextStartEvent,
    ThinkingBudgets,
    ThinkingContent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingLevel,
    ThinkingLevelMap,
    ThinkingStartEvent,
    Tool,
    ToolCall,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
    ToolDetails,
    ToolResultMessage,
    Trace,
    TraceSpan,
    Transport,
    Usage,
    UserMessage,
    VercelGatewayRouting,
    now_ms,
)
from .auth import (
    ApiKeyCredential,
    InMemoryCredentialStore,
    env_api_key_auth,
)
from .auth.resolve import ModelsError
from .api.api_provider_registry import (
    ApiProvider,
    ApiStreamFunction,
    get_api_provider,
    get_api_providers,
    register_api_provider,
    register_builtin_api_providers,
    reset_api_providers,
    unregister_api_providers,
)
from .models import Models
from .provider import Provider, create_provider
from .providers import (
    DEEPSEEK_MODELS,
    FAUX_MODEL,
    OLLAMA_MODELS,
    OPENAI_MODELS,
    deepseek_provider,
    faux_assistant_message,
    faux_provider,
    faux_text,
    faux_thinking,
    faux_tool_call,
    ollama_provider,
    openai_provider,
)
from .providers.all import create_default_models
from .utils import (
    ContextUsageEstimate,
    NON_OVERFLOW_PATTERNS,
    OVERFLOW_PATTERNS,
    RetryCallbacks,
    RetryPolicy,
    calculate_context_tokens,
    compute_backoff_delay,
    estimate_context_tokens,
    estimate_message_tokens,
    estimate_text_and_image_content_tokens,
    estimate_text_tokens,
    estimate_tools_tokens,
    get_overflow_patterns,
    is_context_overflow,
    is_retryable_error,
    retry_assistant_call,
)

__all__ = [
    # Core registry
    "Models",
    "create_default_models",
    # API 注册表（对齐 TS compat.ts apiProviderRegistry）
    "ApiProvider",
    "ApiStreamFunction",
    "register_api_provider",
    "get_api_provider",
    "get_api_providers",
    "unregister_api_providers",
    "register_builtin_api_providers",
    "reset_api_providers",
    # Retry
    "RetryPolicy",
    "RetryCallbacks",
    "retry_assistant_call",
    "is_retryable_error",
    "compute_backoff_delay",
    # Token / Context
    "ContextUsageEstimate",
    "calculate_context_tokens",
    "estimate_context_tokens",
    "estimate_message_tokens",
    "estimate_text_and_image_content_tokens",
    "estimate_text_tokens",
    "estimate_tools_tokens",
    "is_context_overflow",
    "get_overflow_patterns",
    "OVERFLOW_PATTERNS",
    "NON_OVERFLOW_PATTERNS",
    # Provider
    "Provider",
    "create_provider",
    # Provider factories
    "openai_provider",
    "deepseek_provider",
    "ollama_provider",
    "faux_provider",
    # Model lists
    "OPENAI_MODELS",
    "DEEPSEEK_MODELS",
    "OLLAMA_MODELS",
    "FAUX_MODEL",
    # Faux helpers
    "faux_assistant_message",
    "faux_text",
    "faux_thinking",
    "faux_tool_call",
    # Types
    "Model",
    "ApiId",
    "ProviderId",
    "ModelCompat",
    "ModelInput",
    "ModelOutput",
    "Context",
    "MemoryStore",
    "Tool",
    "Message",
    "SystemMessage",
    "UserMessage",
    "AssistantMessage",
    "ToolResultMessage",
    "AgentMessage",
    "BaseMessage",
    "ContentBlock",
    "BaseContent",
    "TextContent",
    "ImageContent",
    "ToolCall",
    "ThinkingContent",
    "CodeContent",
    "Usage",
    "Cost",
    "ToolDetails",
    "AssistantMessageDiagnostic",
    "Trace",
    "TraceSpan",
    "now_ms",
    "StreamOptions",
    # Types (阶段 1 新增)
    "TextSignatureV1",
    "ThinkingLevel",
    "ThinkingLevelMap",
    "ThinkingBudgets",
    "ModelThinkingLevel",
    "StopReason",
    "Transport",
    "CacheRetention",
    "ChatTemplateKwargVar",
    "ChatTemplateKwargValue",
    "ProviderEnv",
    "ProviderHeaders",
    "AsyncHTTPClient",
    "SessionAffinityFormat",
    "ProviderResponse",
    "GrammarFormat",
    "GrammarVariants",
    "JsonSchemaSampling",
    "GrammarSampling",
    "ConstrainedSamplingConfig",
    "ModelCostRates",
    "ModelCostTier",
    "ModelCost",
    "ProviderStreamOptions",
    "SimpleStreamOptions",
    "ImagesOptions",
    "ProviderImagesOptions",
    "KnownImagesApi",
    "KnownImagesProvider",
    "ImagesApi",
    "ImagesProviderId",
    "ImagesStopReason",
    "ImagesInputContent",
    "ImagesOutputContent",
    "ImagesContext",
    "AssistantImages",
    "ImagesModel",
    "OpenAICompletionsCompat",
    "OpenAIResponsesCompat",
    "AnthropicMessagesCompat",
    "BedrockCompat",
    "OpenRouterRouting",
    "VercelGatewayRouting",
    "ProviderStreams",
    "ProviderImages",
    "StreamFunction",
    "ImagesFunction",
    # Events
    "AssistantMessageEvent",
    "calculate_cost",
    "StartEvent",
    "TextStartEvent",
    "TextDeltaEvent",
    "TextEndEvent",
    "ThinkingStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ToolCallStartEvent",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "DoneEvent",
    "ErrorEvent",
    "BaseEvent",
    # Stream
    "AssistantMessageEventStream",
    "EventStream",
    # Auth
    "env_api_key_auth",
    "ApiKeyCredential",
    "InMemoryCredentialStore",
    "ModelsError",
]
